version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
  nginx:
    restart: always
    image: nginx:latest 
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - '/home/ubuntu/ssl/:/ssl/'
      - '/home/ubuntu/ssl_2/:/ssl2/'
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "8001"
    volumes:
      - './backend:/backend'
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8001 backend.wsgi:application"
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - './backend:/backend'
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 backend.wsgi:application"


